// Render the real built frontend on an isolated server with synthetic CRM/Telegram responses.
import assert from 'node:assert/strict';import http from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import {once} from 'node:events';
const require=createRequire('C:/Users/LapTOP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json'),{chromium}=require('playwright');
const out='outputs/contact-messages';await mkdir(out,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/host'){res.setHeader('Content-Type','text/html');return res.end('<iframe title="Bitrix messages" src="/" style="width:100%;height:800px"></iframe>');}if(path!=='/'&&!/^\/assets\/[\w.-]+$/.test(path)){res.writeHead(404);return res.end();}let data=await readFile('packages/frontend/dist'+(path==='/'?'/index.html':path));if(path==='/')data=Buffer.from(data.toString().replace('</head>','<script>window.__B24_CONTEXT__={view:"telegram",dealId:101,domain:"portal.bitrix24.ru",accessToken:"test"};</script></head>'));res.setHeader('Content-Type',/\.m?js$/.test(path)?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404);res.end();}});server.listen(0,'127.0.0.1');await once(server,'listening');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jqWQAAAAASUVORK5CYII=';
const pdf=(()=>{const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length 42 >>\nstream\nBT /F1 18 Tf 30 120 Td (Preview PDF) Tj ET\nendstream'];let text='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(text));text+=(i+1)+' 0 obj\n'+objects[i]+'\nendobj\n';}const xref=Buffer.byteLength(text);text+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Root 1 0 R /Size 6 >>\nstartxref\n'+xref+'\n%%EOF';return Buffer.from(text);})();
let denied=false,multiple=false,accounts=[],delaySergey=false,bindCalled=false,mediaRequests=0,slowMedia=false,pdfMedia=false;
const conversations=[{accountId:'a',chatId:'300',contactId:7,title:'Клиент',manager:'Сергей',enabled:true,status:'ready',lastSync:null},{accountId:'b',chatId:'301',contactId:7,title:'Клиент',manager:'Иван',enabled:true,status:'ready',lastSync:null}];
try{
 await page.route('**/api/**',async route=>{const action=new URL(route.request().url()).pathname.split('/').pop(),body=route.request().postDataJSON();let result={ok:true},status=200;
 if(action==='client-context')result={ok:true,contacts:[{id:7,title:'Тестовый клиент'},...(multiple?[{id:8,title:'Другой клиент'}]:[])],dialogs:conversations,pendingMigration:0};
 if(action==='client-history'){if(body.accountId==='a'&&delaySergey)await new Promise(r=>setTimeout(r,500));if(denied){result={ok:false,error:'Нет доступа к контакту'};status=403;}else result={ok:true,messages:[{id:1,date:'2026-10-09T09:00:00.000Z',outgoing:false,text:body.accountId==='a'?'Сообщение Сергею <script>window.bad=true</script>':'Сообщение Ивану',attachment:body.accountId==='a'?'Голосовое сообщение':'Фото'},{id:2,date:'2026-10-09T09:01:00.000Z',outgoing:true,text:'Ответ прежнего менеджера',manager:'Вася',attachment:null},{id:3,date:'2026-10-09T09:02:00.000Z',outgoing:true,text:'Ответ нового менеджера',manager:'Петя',attachment:null}],next:null};}
 if(action==='media'){mediaRequests++;if(slowMedia)await new Promise(r=>setTimeout(r,500));const image=body.accountId==='b';const wav=Buffer.alloc(16044);wav.write('RIFF');wav.writeUInt32LE(16036,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(16000,40);await route.fulfill({status:200,headers:{'content-type':pdfMedia?'application/pdf':image?'image/png':'audio/wav','cache-control':'no-store','x-media-name':encodeURIComponent(pdfMedia?'Документ.pdf':image?'Фото':'Голосовое')},body:pdfMedia?pdf:image?Buffer.from(pixel.split(',')[1],'base64'):wav});return;}
 if(action==='accounts')result={ok:true,configured:true,accounts};
 if(action==='connect'){accounts=[{id:'a',label:body.label,phase:'qr',qr:pixel,error:'',active:false,lastSync:null,autoBinding:{enabled:true,matched:0,lastRun:null,error:''}}];result={ok:true,account:accounts[0]};}
 if(action==='rename'){assert.equal(body.expectedLabel,accounts[0].label);accounts[0].label=body.label;result={ok:true,account:accounts[0]};}
 if(action==='password'){accounts[0].phase='ready';accounts[0].qr=null;accounts[0].active=true;}
 if(action==='dialogs')result={ok:true,dialogs:[{id:'300',title:'Клиент',binding:null}]};
 if(action==='bind-contact'){assert.equal(body.contactId,7);assert.equal(body.dealId,101);bindCalled=true;result={ok:true,contact:{id:7,title:'Клиент'}};}
 if(action==='history'||action==='bind')throw Error('Retired deal API called');
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(result)});
 });
 await page.addInitScript(()=>{window.previewUrls=[];window.revokedPreviews=[];const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);window.previewUrls.push(url);return url;};URL.revokeObjectURL=url=>{window.revokedPreviews.push(url);revoke(url);};});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('heading',{name:'Сообщения',exact:true}).waitFor();
 await page.getByRole('button',{name:'Диалог · Сергей'}).click();await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.bad),undefined);
 await page.locator('.tg-message').filter({hasText:'Ответ прежнего менеджера'}).getByText('Вася',{exact:true}).waitFor();await page.locator('.tg-message').filter({hasText:'Ответ нового менеджера'}).getByText('Петя',{exact:true}).waitFor();
 assert.equal(mediaRequests,0);await page.getByRole('button',{name:'Прослушать',exact:true}).click();await page.locator('audio').waitFor();await page.waitForFunction(()=>document.querySelector('audio')?.readyState>=1);assert.equal(mediaRequests,1);const firstUrl=await page.locator('audio').getAttribute('src');await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Просмотр вложения'}).waitFor({state:'detached'});assert.equal(await page.evaluate(url=>window.revokedPreviews.includes(url),firstUrl),true);
 await page.getByRole('button',{name:'Прослушать',exact:true}).click();await page.locator('audio').waitFor();assert.equal(mediaRequests,2);assert.notEqual(await page.locator('audio').getAttribute('src'),firstUrl);await page.getByRole('button',{name:'Закрыть просмотр'}).click();
 slowMedia=true;await page.getByRole('button',{name:'Прослушать',exact:true}).click();await page.getByText('Загружаем из Telegram…').waitFor();await page.getByRole('button',{name:'Закрыть просмотр'}).click();await page.waitForTimeout(650);assert.equal(await page.locator('audio').count(),0);slowMedia=false;
 await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.getByText('Сообщение Ивану',{exact:true}).waitFor();assert.equal(await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).count(),0);
 delaySergey=true;await page.getByRole('button',{name:'Диалог · Сергей'}).click();await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.waitForTimeout(650);assert.equal(await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).count(),0);delaySergey=false;
 for(const width of [1280,768,360]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`${out}/messages-${width}.png`,fullPage:true});}
 await page.getByRole('button',{name:'WhatsApp',exact:true}).click();await page.getByRole('heading',{name:'WhatsApp ещё не подключён к CRM'}).waitFor();assert.equal(await page.getByText('Сообщение Ивану',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Telegram',exact:true}).click();multiple=true;await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByLabel('Клиент сделки').selectOption('8');assert.equal(await page.getByRole('button',{name:'Диалог · Иван'}).count(),0);await page.getByLabel('Клиент сделки').selectOption('7');
 await page.getByRole('button',{name:'Аккаунты и привязки',exact:true}).first().click();await page.getByLabel('Название рабочего аккаунта').fill('Рабочий Сергей');await page.getByRole('button',{name:'Подключить аккаунт по QR',exact:true}).click();await page.getByAltText('QR-код входа в рабочий Telegram').waitFor();
 accounts[0].phase='password';accounts[0].qr=null;await page.getByLabel('Пароль двухэтапной проверки').waitFor();await page.getByLabel('Пароль двухэтапной проверки').fill('test-password');await page.getByRole('button',{name:'Подтвердить вход',exact:true}).click();await page.getByRole('button',{name:'Выбрать диалог',exact:true}).click();await page.getByRole('button',{name:'Привязать к контакту',exact:true}).click();assert.equal(bindCalled,true);
 assert.equal(await page.getByRole('button',{name:'Включить автопривязку',exact:true}).count(),0);await page.getByRole('button',{name:'Переименовать менеджера',exact:true}).click();await page.getByLabel('Новое имя менеджера').fill('Пётр');await page.screenshot({path:out+'/rename-mobile.png',fullPage:true});await page.getByRole('button',{name:'Сохранить имя',exact:true}).click();await page.getByText('Имя изменено для последующих сообщений. Прежние подписи сохранены.').waitFor();assert.equal(accounts[0].label,'Пётр');
 await page.getByRole('button',{name:'К сообщениям',exact:true}).click();await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.getByText('Сообщение Ивану',{exact:true}).waitFor();denied=true;await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByRole('alert').filter({hasText:'Нет доступа к контакту'}).waitFor();assert.equal(await page.getByText('Сообщение Ивану',{exact:true}).count(),0);
 await page.addStyleTag({content:'.msg-workspace{font-size:30px}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement!==document.body),true);assert.deepEqual(errors,[]);
 denied=false;multiple=false;await page.setViewportSize({width:1280,height:900});await page.goto('http://127.0.0.1:'+server.address().port+'/host');const frame=page.frameLocator('iframe');await frame.getByRole('button',{name:'Диалог · Иван'}).click();await frame.getByRole('button',{name:'Просмотр',exact:true}).click();await frame.locator('dialog img').waitFor();await page.screenshot({path:out+'/media-preview.png'});const child=page.frames().find(f=>f!==page.mainFrame());const imageUrl=await frame.locator('dialog img').getAttribute('src');await page.evaluate(()=>document.querySelector('iframe').style.display='none');await page.waitForTimeout(1600);assert.equal(await child.evaluate(()=>!document.querySelector('dialog')?.open),true);assert.equal(await child.evaluate(url=>window.revokedPreviews.includes(url),imageUrl),true);await page.evaluate(()=>document.querySelector('iframe').style.display='block');const beforeRepeat=mediaRequests;await frame.getByRole('button',{name:'Просмотр',exact:true}).click();await frame.locator('dialog img').waitFor();assert.equal(mediaRequests,beforeRepeat+1);await child.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide')));await page.waitForTimeout(50);assert.equal(await child.evaluate(()=>!document.querySelector('dialog')?.open),true);assert.deepEqual(errors,[]);
 pdfMedia=true;await frame.getByRole('button',{name:'Просмотр',exact:true}).click();await frame.locator('canvas[data-ready=true]').waitFor();assert.equal(await frame.locator('canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,c.width,c.height).data).some((v,i)=>i%4!==3&&v<100)),true);await page.screenshot({path:out+'/pdf-preview.png'});assert.equal(page.frames().some(f=>f.url().startsWith('chrome-error:')),false);const pdfWorkers=page.workers();assert.ok(pdfWorkers.length>0);await page.evaluate(()=>document.querySelector('iframe').style.display='none');await page.waitForTimeout(1600);assert.equal(await child.evaluate(()=>document.querySelector('canvas')?.width??0),0);assert.equal(page.workers().length,0);await page.evaluate(()=>document.querySelector('iframe').style.display='block');assert.deepEqual(errors,[]);
 console.log('Messages UI passed: split manager dialogs, stale-response isolation, contact switch, messenger switch, QR/password/contact binding, XSS, revoked access, 360/768/1280, enlarged text, keyboard, audio playback metadata, repeated download, pending cancellation, hidden iframe and pagehide cleanup, PDF canvas render/worker teardown, historical sender names, rename form. Synthetic data only.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
