// Render the real built frontend on an isolated server with synthetic CRM/Telegram responses.
import assert from 'node:assert/strict';import http from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import {once} from 'node:events';
const require=createRequire('C:/Users/LapTOP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json'),{chromium}=require('playwright');
const out='outputs/contact-messages';await mkdir(out,{recursive:true});
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path!=='/'&&!/^\/assets\/[\w.-]+$/.test(path)){res.writeHead(404);return res.end();}let data=await readFile('packages/frontend/dist'+(path==='/'?'/index.html':path));if(path==='/')data=Buffer.from(data.toString().replace('</head>','<script>window.__B24_CONTEXT__={view:"telegram",dealId:101,domain:"portal.bitrix24.ru",accessToken:"test"};</script></head>'));res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(data);}catch{res.writeHead(404);res.end();}});server.listen(0,'127.0.0.1');await once(server,'listening');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const pixel='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jqWQAAAAASUVORK5CYII=';
let denied=false,multiple=false,accounts=[],delaySergey=false,bindCalled=false;
const conversations=[{accountId:'a',chatId:'300',contactId:7,title:'Клиент',manager:'Сергей',enabled:true,status:'ready',lastSync:null},{accountId:'b',chatId:'301',contactId:7,title:'Клиент',manager:'Иван',enabled:true,status:'ready',lastSync:null}];
try{
 await page.route('**/api/**',async route=>{const action=new URL(route.request().url()).pathname.split('/').pop(),body=route.request().postDataJSON();let result={ok:true},status=200;
 if(action==='client-context')result={ok:true,contacts:[{id:7,title:'Тестовый клиент'},...(multiple?[{id:8,title:'Другой клиент'}]:[])],dialogs:conversations,pendingMigration:0};
 if(action==='client-history'){if(body.accountId==='a'&&delaySergey)await new Promise(r=>setTimeout(r,500));if(denied){result={ok:false,error:'Нет доступа к контакту'};status=403;}else result={ok:true,messages:[{id:1,date:'2026-10-09T09:00:00.000Z',outgoing:false,text:body.accountId==='a'?'Сообщение Сергею <script>window.bad=true</script>':'Сообщение Ивану',attachment:null}],next:null};}
 if(action==='accounts')result={ok:true,configured:true,accounts};
 if(action==='connect'){accounts=[{id:'a',label:body.label,phase:'qr',qr:pixel,error:'',active:false,lastSync:null}];result={ok:true,account:accounts[0]};}
 if(action==='password'){accounts[0].phase='ready';accounts[0].qr=null;accounts[0].active=true;}
 if(action==='dialogs')result={ok:true,dialogs:[{id:'300',title:'Клиент',binding:null}]};
 if(action==='bind-contact'){assert.equal(body.contactId,7);assert.equal(body.dealId,101);bindCalled=true;result={ok:true,contact:{id:7,title:'Клиент'}};}
 if(action==='history'||action==='bind')throw Error('Retired deal API called');
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(result)});
 });
 await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('heading',{name:'Сообщения',exact:true}).waitFor();
 await page.getByRole('button',{name:'Диалог · Сергей'}).click();await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.bad),undefined);
 await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.getByText('Сообщение Ивану',{exact:true}).waitFor();assert.equal(await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).count(),0);
 delaySergey=true;await page.getByRole('button',{name:'Диалог · Сергей'}).click();await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.waitForTimeout(650);assert.equal(await page.getByText('Сообщение Сергею <script>window.bad=true</script>',{exact:true}).count(),0);delaySergey=false;
 for(const width of [1280,768,360]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`${out}/messages-${width}.png`,fullPage:true});}
 await page.getByRole('button',{name:'WhatsApp',exact:true}).click();await page.getByRole('heading',{name:'WhatsApp ещё не подключён к CRM'}).waitFor();assert.equal(await page.getByText('Сообщение Ивану',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Telegram',exact:true}).click();multiple=true;await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByLabel('Клиент сделки').selectOption('8');assert.equal(await page.getByRole('button',{name:'Диалог · Иван'}).count(),0);await page.getByLabel('Клиент сделки').selectOption('7');
 await page.getByRole('button',{name:'Аккаунты и привязки',exact:true}).first().click();await page.getByLabel('Название рабочего аккаунта').fill('Рабочий Сергей');await page.getByRole('button',{name:'Подключить аккаунт по QR',exact:true}).click();await page.getByAltText('QR-код входа в рабочий Telegram').waitFor();
 accounts[0].phase='password';accounts[0].qr=null;await page.getByLabel('Пароль двухэтапной проверки').waitFor();await page.getByLabel('Пароль двухэтапной проверки').fill('test-password');await page.getByRole('button',{name:'Подтвердить вход',exact:true}).click();await page.getByRole('button',{name:'Выбрать диалог',exact:true}).click();await page.getByRole('button',{name:'Привязать к контакту',exact:true}).click();assert.equal(bindCalled,true);
 await page.getByRole('button',{name:'К сообщениям',exact:true}).click();await page.getByRole('button',{name:'Диалог · Иван'}).click();await page.getByText('Сообщение Ивану',{exact:true}).waitFor();denied=true;await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByRole('alert').filter({hasText:'Нет доступа к контакту'}).waitFor();assert.equal(await page.getByText('Сообщение Ивану',{exact:true}).count(),0);
 await page.addStyleTag({content:'.msg-workspace{font-size:30px}'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement!==document.body),true);assert.deepEqual(errors,[]);
 console.log('Messages UI passed: split manager dialogs, stale-response isolation, contact switch, messenger switch, QR/password/contact binding, XSS, revoked access, 360/768/1280, enlarged text, keyboard. Synthetic data only.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
