import { AttachmentViewer } from './AttachmentViewer.js';
import type { MediaTarget } from './telegram-media.js';
import { useCallback, useEffect, useRef, useState } from 'react';
import { telegramApi, whatsappApi, type TelegramApi } from './telegram-api.js';
import { TelegramWorkspace } from './TelegramWorkspace.js';
import './messages.css';
interface Contact { id:number;title:string }
interface Conversation {kind?:'private'|'group';sourceError?:string; contactId:number;accountId:string;chatId:string;title:string;manager:string;enabled:boolean;status:string;lastSync:string|null }
interface Entry {author?:string;id:number;date:string;outgoing:boolean;text:string;attachment:string|null;edited?:boolean;deleted?:boolean;manager:string;dialog:string}
interface Context {contacts:Contact[];dialogs:Conversation[];pendingMigration:number}
const empty:Context={contacts:[],dialogs:[],pendingMigration:0};
const key=(d:Conversation)=>`${d.accountId}:${d.chatId}`;
export function MessagesWorkspace({dealId,api=telegramApi,waApi=whatsappApi}:{dealId:number|null;api?:TelegramApi;waApi?:TelegramApi}):JSX.Element {
 const [context,setContext]=useState<Context>(empty),[contact,setContact]=useState<number|null>(null),[messenger,setMessenger]=useState('telegram'),[conversation,setConversation]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[next,setNext]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reading,setReading]=useState(false),[managing,setManaging]=useState(false);
 const activeApi=messenger==='whatsapp'?waApi:api,brand=messenger==='whatsapp'?'WhatsApp':'Telegram';
 const [contextMessenger,setContextMessenger]=useState('');
 const [mediaTarget,setMediaTarget]=useState<MediaTarget|null>(null);
 const closeMedia=useCallback(()=>setMediaTarget(null),[]);
 const expanded=useRef(false);
 const contextSequence=useRef(0),historySequence=useRef(0),alive=useRef(true);
 const clear=()=>{setMediaTarget(null);expanded.current=false;historySequence.current++;setEntries([]);setNext(null);setConversation('');};
 const loadContext=useCallback(async()=>{if(!dealId){setLoading(false);return;}const seq=++contextSequence.current;
  try{const result=await activeApi<Context>('client-context',{dealId});if(!alive.current||seq!==contextSequence.current)return;setContext(result);setContextMessenger(messenger);setContact(old=>result.contacts.some(c=>c.id===old)?old:result.contacts.length===1?result.contacts[0]!.id:null);setError('');}
  catch(e){if(alive.current&&seq===contextSequence.current){historySequence.current++;setMediaTarget(null);setContext(empty);setContact(null);setConversation('');setEntries([]);setNext(null);setError(e instanceof Error?e.message:'Не удалось проверить доступ к клиенту');}}
  finally{if(alive.current&&seq===contextSequence.current)setLoading(false);}
 },[activeApi,dealId,messenger]);
 useEffect(()=>{alive.current=true;setContext(empty);setContact(null);clear();setLoading(true);void loadContext();const timer=setInterval(()=>{if(!document.hidden)void loadContext();},15000);return()=>{alive.current=false;contextSequence.current++;historySequence.current++;clearInterval(timer);};},[loadContext]);
 const dialogs=contextMessenger===messenger?context.dialogs.filter(d=>d.contactId===contact):[],selected=dialogs.find(d=>key(d)===conversation);
 const read=useCallback(async(before?:string)=>{if(!dealId||!contact||!selected||messenger==='max')return;const seq=++historySequence.current;setReading(true);
  try{const result=await activeApi<{messages:Entry[];next:string|null}>('client-history',{dealId,contactId:contact,accountId:selected.accountId,chatId:selected.chatId,...(before?{before}:{})});if(!alive.current||seq!==historySequence.current)return;
   setEntries(old=>before||expanded.current?[...new Map([...old,...result.messages].map(m=>[m.id,m])).values()].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id):result.messages);setNext(old=>before||!expanded.current?result.next:old);if(before)expanded.current=true;setError('');
  }catch(e){if(alive.current&&seq===historySequence.current){setMediaTarget(null);setEntries([]);setNext(null);setError(e instanceof Error?e.message:'Не удалось загрузить сообщения');}}
  finally{if(alive.current&&seq===historySequence.current)setReading(false);}
 },[activeApi,dealId,contact,selected?.accountId,selected?.chatId,messenger]);
 useEffect(()=>{setMediaTarget(null);expanded.current=false;historySequence.current++;setEntries([]);setNext(null);setReading(false);if(!selected||managing||messenger==='max')return;void read();const timer=setInterval(()=>{if(!document.hidden)void read();},15000);return()=>{historySequence.current++;clearInterval(timer);};},[read,managing]);
 useEffect(()=>{if(mediaTarget&&entries.some(m=>m.id===mediaTarget.messageId&&(m.deleted||!m.attachment)))setMediaTarget(null);},[entries,mediaTarget]);
 return <main className="msg-workspace"><header className="msg-header"><div><h1>Сообщения</h1><p>Переписка клиента во всех его сделках</p></div><div className="msg-actions"><button onClick={()=>{clear();setManaging(v=>!v);}}>{managing?'К сообщениям':'Аккаунты и привязки'}</button><button disabled={loading||reading} onClick={()=>void loadContext().then(()=>read())}>Обновить</button></div></header>
 {error&&<p role="alert" className="tg-error">{error}</p>}
 {loading?<p role="status">Проверяем клиента сделки…</p>:<>
 {dealId&&context.contacts.length>1?<label className="msg-contact">Клиент сделки<select value={contact??''} onChange={e=>{clear();setContact(e.target.value?Number(e.target.value):null);}}><option value="">Выберите контакт</option>{context.contacts.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>:context.contacts[0]?<p className="msg-client"><strong>{context.contacts[0].title}</strong><span>Контакт № {context.contacts[0].id}</span></p>:dealId&&!error?<p className="tg-empty">Нет доступного контакта сделки. Добавьте контакт в Битрикс24 или проверьте права на него.</p>:null}
 {context.pendingMigration>0&&<p className="tg-notice">Для части прежних привязок нужно проверить контакт. Сохранённые сообщения не удалены. Откройте «Аккаунты и привязки».</p>}
 <nav className="msg-messengers" aria-label="Мессенджер">{[['telegram','Telegram'],['whatsapp','WhatsApp'],['max','MAX']].map(([id,title])=><button key={id} aria-pressed={messenger===id} onClick={()=>{clear();setMessenger(id!);setManaging(false);}}>{title}</button>)}</nav>
 {messenger==='max'?<section className="tg-empty"><h2>MAX ещё не подключён к CRM</h2><p>Рабочая интеграция этого мессенджера пока не настроена.</p></section>:managing||!dealId?<TelegramWorkspace key={`${messenger}:${contact??'none'}`} messenger={messenger==='whatsapp'?'whatsapp':'telegram'} dealId={dealId} contactId={contact} managementOnly api={activeApi}/>:contact?<div className="msg-layout"><aside className="msg-dialogs"><h2>Диалоги и группы</h2>{dialogs.length?dialogs.map(d=><button key={key(d)} className="msg-dialog" aria-pressed={conversation===key(d)} onClick={()=>{historySequence.current++;setEntries([]);setNext(null);setConversation(key(d));}}><strong>{d.kind==='group'?`Группа · ${d.title}`:`Диалог · ${d.manager}`}</strong><span>{d.kind==='group'?`Сбор через ${d.manager}`:d.title}</span><small>{d.sourceError||(!d.enabled?'Сбор приостановлен':d.status==='ready'?'Подключён':d.status==='login_required'?'Нужен повторный вход по QR':'Соединение недоступно · сохранённая история доступна')}</small></button>):<p>Пока нет привязанных диалогов {brand}.</p>}</aside><section className="msg-thread" aria-label="Выбранный диалог">{selected?<><h2>{selected.kind==='group'?`Группа · ${selected.title}`:`Диалог · ${selected.manager}`}</h2>{selected.kind==='group'&&<p className="msg-hint">Общая группа · сбор через {selected.manager}. Здесь видны сообщения всех участников.</p>}{selected.sourceError&&<p role="status" className="tg-notice">{selected.sourceError}</p>}<p className="msg-hint">Ответы отправляйте в {brand}. Здесь видна общая история этого диалога по всем сделкам клиента.</p>{next&&<button disabled={reading} onClick={()=>void read(next)}>Более ранние сообщения</button>}{reading&&<p role="status">Загружаем сообщения…</p>}<ol className="tg-messages">{entries.map(m=><li key={m.id} className={m.outgoing?'tg-message tg-outgoing':'tg-message'}><div className="tg-message-meta"><strong>{selected.kind==='group'?(m.author||`Автор не указан ${brand}`):m.outgoing?m.manager:selected.title}</strong><time dateTime={m.date}>{new Date(m.date).toLocaleString('ru-RU')}</time></div>{m.deleted?<p className="tg-muted">Сообщение удалено в {brand}</p>:<><p>{m.text}</p>{m.attachment&&<div className="tg-attachment"><span>{m.attachment}</span> <button onClick={()=>setMediaTarget({messenger:messenger==='whatsapp'?'whatsapp':'telegram',dealId:dealId!,contactId:contact,accountId:selected.accountId,chatId:selected.chatId,messageId:m.id})}>{/голос|аудио/i.test(m.attachment)?'Прослушать':'Просмотр'}</button></div>}{m.edited&&<small>Изменено</small>}</>}</li>)}</ol>{!entries.length&&!reading&&!error&&<p>Сообщения ещё не получены.</p>}</>:<div className="tg-empty"><h2>Выберите диалог или группу</h2><p>Личные диалоги менеджеров и общие группы показаны отдельно. Сообщения разных диалогов не смешиваются.</p></div>}</section></div>:null}
 </>}
 {mediaTarget&&<AttachmentViewer key={`${mediaTarget.accountId}:${mediaTarget.chatId}:${mediaTarget.messageId}`} target={mediaTarget} onClose={closeMedia}/>}
 </main>;
}
