CREATE TABLE IF NOT EXISTS workflow_documents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    document_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    external_system VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    external_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    external_revision_key VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    external_status VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    external_docstatus TINYINT UNSIGNED NULL,
    bitrix_deal_id BIGINT UNSIGNED NULL,
    source_created_at DATETIME(6) NULL,
    source_modified_at DATETIME(6) NULL,
    observed_at DATETIME(6) NOT NULL,
    source_hash BINARY(32) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_documents_external (external_system, document_type, external_id),
    KEY ix_workflow_documents_revision (document_type, external_revision_key),
    KEY ix_workflow_documents_deal_type (bitrix_deal_id, document_type),
    KEY ix_workflow_documents_type_status (document_type, external_status),
    KEY ix_workflow_documents_observed_at (observed_at),
    CONSTRAINT chk_workflow_documents_type CHECK (document_type IN ('supply_request', 'purchase_order', 'purchase_receipt', 'transfer', 'stock_entry')),
    CONSTRAINT chk_workflow_documents_system CHECK (external_system IN ('erpnext', 'bitrix')),
    CONSTRAINT chk_workflow_documents_external_id CHECK (CHAR_LENGTH(external_id) > 0),
    CONSTRAINT chk_workflow_documents_revision CHECK (external_revision_key IS NULL OR CHAR_LENGTH(external_revision_key) > 0),
    CONSTRAINT chk_workflow_documents_docstatus CHECK (external_docstatus IS NULL OR external_docstatus IN (0, 1, 2)),
    CONSTRAINT chk_workflow_documents_deal CHECK (bitrix_deal_id IS NULL OR bitrix_deal_id > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
