CREATE TABLE IF NOT EXISTS workflow_document_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    document_id BIGINT UNSIGNED NOT NULL,
    external_line_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    line_ordinal INT UNSIGNED NOT NULL,
    erp_item_code VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    planned_qty DECIMAL(21, 9) NULL,
    request_qty DECIMAL(21, 9) NULL,
    actual_qty DECIMAL(21, 9) NULL,
    source_warehouse VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    target_warehouse VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    source_modified_at DATETIME(6) NULL,
    observed_at DATETIME(6) NOT NULL,
    source_hash BINARY(32) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_document_lines_external (document_id, external_line_key),
    UNIQUE KEY uq_workflow_document_lines_ordinal (document_id, line_ordinal),
    KEY ix_workflow_document_lines_item (erp_item_code),
    KEY ix_workflow_document_lines_observed_at (observed_at),
    CONSTRAINT fk_workflow_document_lines_document FOREIGN KEY (document_id) REFERENCES workflow_documents (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_workflow_document_lines_item CHECK (CHAR_LENGTH(erp_item_code) > 0),
    CONSTRAINT chk_workflow_document_lines_quantity CHECK (planned_qty IS NOT NULL OR request_qty IS NOT NULL OR actual_qty IS NOT NULL),
    CONSTRAINT chk_workflow_document_lines_planned CHECK (planned_qty IS NULL OR planned_qty >= 0),
    CONSTRAINT chk_workflow_document_lines_request CHECK (request_qty IS NULL OR request_qty >= 0),
    CONSTRAINT chk_workflow_document_lines_actual CHECK (actual_qty IS NULL OR actual_qty >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
