CREATE TABLE IF NOT EXISTS workflow_line_allocations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_line_id BIGINT UNSIGNED NOT NULL,
    target_line_id BIGINT UNSIGNED NOT NULL,
    allocation_type VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    quantity DECIMAL(21, 9) NOT NULL,
    evidence_kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    evidence_source VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    source_hash BINARY(32) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_line_allocations_relation (source_line_id, target_line_id, allocation_type),
    KEY ix_workflow_line_allocations_target (target_line_id, allocation_type),
    KEY ix_workflow_line_allocations_observed_at (observed_at),
    CONSTRAINT fk_workflow_line_allocations_source FOREIGN KEY (source_line_id) REFERENCES workflow_document_lines (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_workflow_line_allocations_target FOREIGN KEY (target_line_id) REFERENCES workflow_document_lines (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_workflow_line_allocations_type CHECK (allocation_type IN ('ordered', 'received', 'transferred', 'fulfilled', 'cancelled')),
    CONSTRAINT chk_workflow_line_allocations_evidence CHECK (evidence_kind IN ('explicit_external_field', 'native_erp_link', 'derived_match')),
    CONSTRAINT chk_workflow_line_allocations_distinct CHECK (source_line_id <> target_line_id),
    CONSTRAINT chk_workflow_line_allocations_quantity CHECK (quantity > 0),
    CONSTRAINT chk_workflow_line_allocations_source CHECK (CHAR_LENGTH(evidence_source) > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
