CREATE TABLE IF NOT EXISTS tilda_product_mappings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tilda_uid VARCHAR(64) NOT NULL,
    tilda_external_id VARCHAR(191) NOT NULL,
    tilda_sku VARCHAR(120) NULL,
    tilda_title VARCHAR(255) NOT NULL,
    row_kind VARCHAR(16) NOT NULL,
    parent_tilda_uid VARCHAR(64) NULL,
    variant_label VARCHAR(255) NULL,
    erp_item_code VARCHAR(191) NULL,
    mapping_status VARCHAR(16) NOT NULL,
    audit_source VARCHAR(191) NOT NULL,
    source_seen_at DATETIME(6) NOT NULL,
    confirmed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_tilda_product_mappings_uid (tilda_uid),
    UNIQUE KEY uq_tilda_product_mappings_external (tilda_external_id),
    KEY ix_tilda_product_mappings_sku (tilda_sku),
    KEY ix_tilda_product_mappings_erp (erp_item_code),
    KEY ix_tilda_product_mappings_status (mapping_status, updated_at),
    KEY ix_tilda_product_mappings_parent (parent_tilda_uid),
    CONSTRAINT chk_tilda_product_mappings_status CHECK (mapping_status IN ('confirmed', 'unresolved', 'ignored')),
    CONSTRAINT chk_tilda_product_mappings_kind CHECK (row_kind IN ('parent', 'variant')),
    CONSTRAINT chk_tilda_product_mappings_parent CHECK ((row_kind = 'parent' AND parent_tilda_uid IS NULL) OR (row_kind = 'variant' AND parent_tilda_uid IS NOT NULL)),
    CONSTRAINT chk_tilda_product_mappings_self CHECK (parent_tilda_uid IS NULL OR parent_tilda_uid <> tilda_uid),
    CONSTRAINT chk_tilda_product_mappings_confirmed CHECK (mapping_status <> 'confirmed' OR (tilda_sku IS NOT NULL AND erp_item_code IS NOT NULL AND confirmed_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
