CREATE TABLE IF NOT EXISTS tilda_stock_sync_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_uuid CHAR(36) NOT NULL,
    trigger_source VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    projection_hash BINARY(32) NULL,
    content_hash_before BINARY(32) NULL,
    content_hash_after BINARY(32) NULL,
    target_count INT UNSIGNED NULL,
    difference_count_before INT UNSIGNED NULL,
    difference_count_after INT UNSIGNED NULL,
    blocked_count INT UNSIGNED NULL,
    catalog_xml_hash BINARY(32) NULL,
    projection_xml_hash BINARY(32) NULL,
    rollback_xml_hash BINARY(32) NULL,
    error_phase VARCHAR(32) NULL,
    error_message VARCHAR(500) NULL,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_tilda_stock_sync_runs_uuid (run_uuid),
    KEY ix_tilda_stock_sync_runs_status_started (status, started_at),
    KEY ix_tilda_stock_sync_runs_projection (projection_hash, started_at),
    CONSTRAINT chk_tilda_stock_sync_runs_source CHECK (trigger_source IN ('scheduled', 'manual')),
    CONSTRAINT chk_tilda_stock_sync_runs_status CHECK (status IN ('running', 'no_op', 'verified', 'failed')),
    CONSTRAINT chk_tilda_stock_sync_runs_finished CHECK ((status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL)),
    CONSTRAINT chk_tilda_stock_sync_runs_error CHECK ((status = 'failed' AND error_phase IS NOT NULL AND error_message IS NOT NULL) OR (status <> 'failed' AND error_phase IS NULL AND error_message IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
