CREATE TABLE IF NOT EXISTS stock_reservation_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_system VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    source_revision_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    requested_expires_at DATETIME(6) NOT NULL,
    approved_expires_at DATETIME(6) NULL,
    requested_by VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_by VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    reviewed_at DATETIME(6) NULL,
    rejection_reason VARCHAR(500) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservation_requests_key (request_key),
    UNIQUE KEY uq_stock_reservation_requests_source (source_system, source_type, source_id, source_revision_key),
    KEY ix_stock_reservation_requests_status (status, requested_at),
    CONSTRAINT chk_stock_reservation_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn')),
    CONSTRAINT chk_stock_reservation_requests_source CHECK (CHAR_LENGTH(source_id) > 0 AND CHAR_LENGTH(source_revision_key) > 0),
    CONSTRAINT chk_stock_reservation_requests_actor CHECK (CHAR_LENGTH(requested_by) > 0),
    CONSTRAINT chk_stock_reservation_requests_term CHECK (requested_expires_at > requested_at AND (approved_expires_at IS NULL OR approved_expires_at > requested_at)),
    CONSTRAINT chk_stock_reservation_requests_review CHECK ((status = 'pending' AND reviewed_by IS NULL AND reviewed_at IS NULL AND approved_expires_at IS NULL AND rejection_reason IS NULL) OR (status = 'approved' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND approved_expires_at IS NOT NULL AND rejection_reason IS NULL) OR (status = 'rejected' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND rejection_reason IS NOT NULL AND CHAR_LENGTH(rejection_reason) > 0) OR (status = 'withdrawn' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND approved_expires_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
