CREATE TABLE IF NOT EXISTS stock_reservations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reservation_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_system VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    source_revision_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    approved_request_id BIGINT UNSIGNED NULL,
    expires_at DATETIME(6) NULL,
    approved_at DATETIME(6) NOT NULL,
    created_by VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservations_key (reservation_key),
    UNIQUE KEY uq_stock_reservations_source (source_system, source_type, source_id, source_revision_key),
    UNIQUE KEY uq_stock_reservations_approved_request (approved_request_id),
    KEY ix_stock_reservations_status_expiry (status, expires_at),
    KEY ix_stock_reservations_approved (approved_at, id),
    CONSTRAINT fk_stock_reservations_approved_request FOREIGN KEY (approved_request_id) REFERENCES stock_reservation_requests (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservations_source_type CHECK (source_type IN ('deal', 'transfer', 'marketplace', 'presale_repair', 'legacy')),
    CONSTRAINT chk_stock_reservations_status CHECK (status IN ('active', 'consumed', 'released', 'cancelled', 'expired', 'shortfall', 'closed', 'pending_reconcile', 'superseded')),
    CONSTRAINT chk_stock_reservations_source CHECK (CHAR_LENGTH(source_id) > 0 AND CHAR_LENGTH(source_revision_key) > 0),
    CONSTRAINT chk_stock_reservations_actor CHECK (CHAR_LENGTH(created_by) > 0),
    CONSTRAINT chk_stock_reservations_deal_request CHECK (source_type <> 'deal' OR approved_request_id IS NOT NULL),
    CONSTRAINT chk_stock_reservations_expiry CHECK ((source_type = 'deal' AND expires_at IS NOT NULL AND expires_at > approved_at) OR (source_type <> 'deal' AND expires_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
