CREATE TABLE IF NOT EXISTS stock_reservation_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reservation_id BIGINT UNSIGNED NOT NULL,
    source_line_key VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    erp_warehouse_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    item_code VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    reserved_qty DECIMAL(21, 9) NOT NULL,
    consumed_qty DECIMAL(21, 9) NOT NULL DEFAULT 0,
    released_qty DECIMAL(21, 9) NOT NULL DEFAULT 0,
    shortfall_qty DECIMAL(21, 9) NOT NULL DEFAULT 0,
    active_qty DECIMAL(21, 9) GENERATED ALWAYS AS (reserved_qty - consumed_qty - released_qty - shortfall_qty) STORED,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservation_lines_id_header (id, reservation_id),
    UNIQUE KEY uq_stock_reservation_lines_source (reservation_id, source_line_key, erp_warehouse_name, item_code),
    KEY ix_stock_reservation_lines_availability (erp_warehouse_name, item_code, active_qty),
    CONSTRAINT fk_stock_reservation_lines_header FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_reservation_lines_key FOREIGN KEY (erp_warehouse_name, item_code) REFERENCES stock_availability_keys (erp_warehouse_name, item_code) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservation_lines_identity CHECK (CHAR_LENGTH(source_line_key) > 0 AND CHAR_LENGTH(erp_warehouse_name) > 0 AND CHAR_LENGTH(item_code) > 0),
    CONSTRAINT chk_stock_reservation_lines_reserved CHECK (reserved_qty > 0),
    CONSTRAINT chk_stock_reservation_lines_reductions CHECK (consumed_qty >= 0 AND released_qty >= 0 AND shortfall_qty >= 0 AND consumed_qty + released_qty + shortfall_qty <= reserved_qty)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
