CREATE TABLE IF NOT EXISTS stock_reservation_release_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reservation_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    requested_reason VARCHAR(500) NULL,
    requested_by VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_by VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    reviewed_at DATETIME(6) NULL,
    decision_reason VARCHAR(500) NULL,
    pending_reservation_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status = 'pending' THEN reservation_id ELSE NULL END) STORED,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservation_release_requests_key (request_key),
    UNIQUE KEY uq_stock_reservation_release_requests_pending (pending_reservation_id),
    KEY ix_stock_reservation_release_requests_status (status, requested_at),
    CONSTRAINT fk_stock_reservation_release_requests_header FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservation_release_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn')),
    CONSTRAINT chk_stock_reservation_release_requests_actor CHECK (CHAR_LENGTH(requested_by) > 0),
    CONSTRAINT chk_stock_reservation_release_requests_review CHECK ((status = 'pending' AND reviewed_by IS NULL AND reviewed_at IS NULL AND decision_reason IS NULL) OR (status IN ('approved', 'rejected', 'withdrawn') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
