CREATE TABLE IF NOT EXISTS stock_reservation_commands (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    idempotency_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reservation_id BIGINT UNSIGNED NULL,
    reservation_request_id BIGINT UNSIGNED NULL,
    release_request_id BIGINT UNSIGNED NULL,
    command_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_hash BINARY(32) NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    external_doctype VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    external_document_name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
    actor_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    correlation_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    causation_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
    started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservation_commands_idempotency (idempotency_key),
    UNIQUE KEY uq_stock_reservation_commands_external (command_type, external_doctype, external_document_name),
    KEY ix_stock_reservation_commands_reservation (reservation_id, started_at),
    KEY ix_stock_reservation_commands_status (status, started_at),
    CONSTRAINT fk_stock_reservation_commands_header FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_reservation_commands_request FOREIGN KEY (reservation_request_id) REFERENCES stock_reservation_requests (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_reservation_commands_release FOREIGN KEY (release_request_id) REFERENCES stock_reservation_release_requests (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservation_commands_type CHECK (command_type IN ('request_reserve', 'approve_reserve', 'reject_reserve', 'adjust_transfer', 'consume', 'request_release', 'approve_release', 'reject_release', 'expire', 'reconcile_shortfall', 'mark_pending_reconcile', 'supersede')),
    CONSTRAINT chk_stock_reservation_commands_status CHECK (status IN ('started', 'applied', 'failed', 'pending_reconcile')),
    CONSTRAINT chk_stock_reservation_commands_actor CHECK (CHAR_LENGTH(actor_id) > 0),
    CONSTRAINT chk_stock_reservation_commands_external_pair CHECK ((external_doctype IS NULL) = (external_document_name IS NULL)),
    CONSTRAINT chk_stock_reservation_commands_finished CHECK ((status IN ('started', 'pending_reconcile') AND finished_at IS NULL) OR (status IN ('applied', 'failed') AND finished_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
