CREATE TABLE IF NOT EXISTS stock_reservation_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reservation_id BIGINT UNSIGNED NOT NULL,
    reservation_line_id BIGINT UNSIGNED NULL,
    command_id BIGINT UNSIGNED NOT NULL,
    event_index SMALLINT UNSIGNED NOT NULL,
    event_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    quantity DECIMAL(21, 9) NULL,
    from_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    to_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NULL,
    reservation_version BIGINT UNSIGNED NOT NULL,
    actor_id VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    occurred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_reservation_events_command_order (command_id, event_index),
    KEY ix_stock_reservation_events_header_time (reservation_id, occurred_at, id),
    KEY ix_stock_reservation_events_line_time (reservation_line_id, occurred_at, id),
    CONSTRAINT fk_stock_reservation_events_header FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_reservation_events_line FOREIGN KEY (reservation_line_id, reservation_id) REFERENCES stock_reservation_lines (id, reservation_id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_stock_reservation_events_command FOREIGN KEY (command_id) REFERENCES stock_reservation_commands (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_reservation_events_type CHECK (event_type IN ('created', 'consumed', 'released', 'expired', 'cancelled', 'shortfall', 'status_changed', 'pending_reconcile', 'superseded')),
    CONSTRAINT chk_stock_reservation_events_quantity CHECK ((event_type IN ('consumed', 'released', 'shortfall') AND quantity IS NOT NULL AND quantity > 0) OR (event_type NOT IN ('consumed', 'released', 'shortfall') AND quantity IS NULL)),
    CONSTRAINT chk_stock_reservation_events_status_change CHECK (event_type <> 'status_changed' OR (from_status IS NOT NULL AND to_status IS NOT NULL AND from_status <> to_status)),
    CONSTRAINT chk_stock_reservation_events_actor CHECK (CHAR_LENGTH(actor_id) > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
