CREATE TABLE IF NOT EXISTS stock_transfer_revisions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transfer_id BIGINT UNSIGNED NOT NULL,
    revision_no INT UNSIGNED NOT NULL,
    state_hash BINARY(32) NOT NULL,
    source_kind VARCHAR(32) CHARACTER SET ascii NOT NULL,
    supply_request VARCHAR(191) NOT NULL,
    supply_request_key VARCHAR(191) NOT NULL,
    purchase_order VARCHAR(191) NOT NULL,
    deal_id VARCHAR(64) NOT NULL,
    to_store VARCHAR(191) NOT NULL,
    from_store VARCHAR(191) NOT NULL,
    status VARCHAR(32) CHARACTER SET ascii NOT NULL,
    note TEXT NOT NULL,
    task_id BIGINT UNSIGNED NULL,
    ship_entry VARCHAR(191) NULL,
    receive_entry VARCHAR(191) NULL,
    shortage_return_entry VARCHAR(191) NULL,
    correction_of_external_id BIGINT UNSIGNED NULL,
    correction_kind VARCHAR(32) CHARACTER SET ascii NULL,
    source_created_at DATETIME(6) NULL,
    created_by_id VARCHAR(191) NOT NULL,
    created_by_name VARCHAR(255) NOT NULL,
    recorded_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_transfer_revisions_number (transfer_id, revision_no),
    KEY ix_stock_transfer_revisions_hash (transfer_id, state_hash),
    KEY ix_stock_transfer_revisions_status (status, recorded_at),
    CONSTRAINT fk_stock_transfer_revisions_record FOREIGN KEY (transfer_id) REFERENCES stock_transfer_records (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_transfer_revisions_number CHECK (revision_no > 0),
    CONSTRAINT chk_stock_transfer_revisions_source CHECK (source_kind IN ('bitrix_backfill', 'bitrix_dual_write', 'sql_native', 'repair')),
    CONSTRAINT chk_stock_transfer_revisions_status CHECK (status IN ('draft', 'collected', 'in_transit', 'accepted', 'posted', 'canceled', 'requested', 'received', 'shortage')),
    CONSTRAINT chk_stock_transfer_revisions_note CHECK (CHAR_LENGTH(note) <= 10000),
    CONSTRAINT chk_stock_transfer_revisions_correction CHECK (correction_kind IS NULL OR correction_kind IN ('shortage_return', 'overage_transfer'))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
