CREATE TABLE IF NOT EXISTS catalog_mirror_checkpoints (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    snapshot_hash BINARY(32) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    last_verified_at DATETIME(6) NOT NULL,
    source_complete TINYINT(1) NOT NULL,
    erp_item_records INT UNSIGNED NOT NULL,
    erp_price_records INT UNSIGNED NOT NULL,
    erp_bin_records INT UNSIGNED NOT NULL,
    erp_warehouse_records INT UNSIGNED NOT NULL,
    bitrix_product_records INT UNSIGNED NOT NULL,
    product_count INT UNSIGNED NOT NULL,
    attribute_count INT UNSIGNED NOT NULL,
    price_count INT UNSIGNED NOT NULL,
    warehouse_count INT UNSIGNED NOT NULL,
    stock_count INT UNSIGNED NOT NULL,
    applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_catalog_mirror_checkpoints_hash (snapshot_hash),
    UNIQUE KEY uq_catalog_mirror_checkpoints_observed (observed_at),
    KEY ix_catalog_mirror_checkpoints_applied (applied_at),
    KEY ix_catalog_mirror_checkpoints_verified (last_verified_at),
    CONSTRAINT chk_catalog_mirror_checkpoint_complete CHECK (source_complete = 1),
    CONSTRAINT chk_catalog_mirror_checkpoint_sources CHECK (erp_item_records > 0 AND erp_price_records >= 0 AND erp_bin_records >= 0 AND erp_warehouse_records > 0 AND bitrix_product_records > 0),
    CONSTRAINT chk_catalog_mirror_checkpoint_counts CHECK (product_count > 0 AND attribute_count >= 0 AND price_count >= 0 AND warehouse_count > 0 AND stock_count >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
