CREATE TABLE IF NOT EXISTS catalog_mirror_products (
    item_code BIGINT UNSIGNED NOT NULL,
    bitrix_iblock_id INT UNSIGNED NOT NULL,
    bitrix_section_id BIGINT UNSIGNED NULL,
    item_name VARCHAR(500) NOT NULL,
    is_stock_item TINYINT(1) NOT NULL,
    is_marketplace_bundle TINYINT(1) NOT NULL,
    article VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    section_name VARCHAR(255) NOT NULL,
    product_status VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    content_summary TEXT NOT NULL,
    filter_category VARCHAR(255) NOT NULL,
    image_path VARCHAR(1000) NOT NULL,
    image_source VARCHAR(16) CHARACTER SET ascii NOT NULL,
    marketplace_old_id VARCHAR(120) NOT NULL,
    source_modified_at DATETIME(6) NULL,
    observed_at DATETIME(6) NOT NULL,
    source_hash BINARY(32) NOT NULL,
    PRIMARY KEY (item_code),
    KEY ix_catalog_mirror_products_name (item_name),
    KEY ix_catalog_mirror_products_article (article),
    KEY ix_catalog_mirror_products_model (model),
    KEY ix_catalog_mirror_products_section (section_name),
    KEY ix_catalog_mirror_products_observed (observed_at),
    CONSTRAINT chk_catalog_mirror_products_code CHECK (item_code > 0),
    CONSTRAINT chk_catalog_mirror_products_iblock CHECK (bitrix_iblock_id IN (24, 26)),
    CONSTRAINT chk_catalog_mirror_products_section CHECK (bitrix_section_id IS NULL OR bitrix_section_id > 0),
    CONSTRAINT chk_catalog_mirror_products_stock CHECK (is_stock_item IN (0, 1)),
    CONSTRAINT chk_catalog_mirror_products_bundle CHECK (is_marketplace_bundle IN (0, 1)),
    CONSTRAINT chk_catalog_mirror_products_image CHECK (image_source IN ('none', 'erpnext', 'bitrix')),
    CONSTRAINT chk_catalog_mirror_products_name CHECK (CHAR_LENGTH(item_name) > 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
