CREATE TABLE IF NOT EXISTS catalog_mirror_attributes (
    item_code BIGINT UNSIGNED NOT NULL,
    attribute_id VARCHAR(191) NOT NULL,
    attribute_ordinal INT UNSIGNED NOT NULL,
    attribute_key VARCHAR(120) NOT NULL,
    attribute_label VARCHAR(255) NOT NULL,
    attribute_group VARCHAR(255) NOT NULL,
    attribute_type VARCHAR(24) CHARACTER SET ascii NOT NULL,
    raw_value TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    number_value DECIMAL(24, 9) NULL,
    number_min DECIMAL(24, 9) NULL,
    number_max DECIMAL(24, 9) NULL,
    unit VARCHAR(60) NOT NULL,
    boolean_value TINYINT(1) NULL,
    filterable TINYINT(1) NOT NULL,
    observed_at DATETIME(6) NOT NULL,
    source_hash BINARY(32) NOT NULL,
    PRIMARY KEY (item_code, attribute_id),
    KEY ix_catalog_mirror_attributes_order (item_code, attribute_ordinal),
    KEY ix_catalog_mirror_attributes_filter (attribute_key, filterable),
    KEY ix_catalog_mirror_attributes_observed (observed_at),
    CONSTRAINT fk_catalog_mirror_attributes_product FOREIGN KEY (item_code) REFERENCES catalog_mirror_products (item_code) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_catalog_mirror_attributes_ordinal CHECK (attribute_ordinal > 0),
    CONSTRAINT chk_catalog_mirror_attributes_type CHECK (attribute_type IN ('text', 'option', 'multi_option', 'number', 'range', 'boolean')),
    CONSTRAINT chk_catalog_mirror_attributes_boolean CHECK (boolean_value IS NULL OR boolean_value IN (0, 1)),
    CONSTRAINT chk_catalog_mirror_attributes_filterable CHECK (filterable IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
