CREATE TABLE IF NOT EXISTS stock_transfer_request_revisions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    request_id BIGINT UNSIGNED NOT NULL,
    revision_no INT UNSIGNED NOT NULL,
    state_hash BINARY(32) NOT NULL,
    source_kind VARCHAR(32) CHARACTER SET ascii NOT NULL,
    request_kind VARCHAR(16) CHARACTER SET ascii NOT NULL,
    request_status VARCHAR(16) CHARACTER SET ascii NOT NULL,
    from_store VARCHAR(191) NOT NULL,
    to_store VARCHAR(191) NOT NULL,
    note VARCHAR(500) NOT NULL,
    source_created_at DATETIME(6) NULL,
    created_by_id VARCHAR(191) NOT NULL,
    created_by_name VARCHAR(255) NOT NULL,
    converted_at DATETIME(6) NULL,
    converted_by_id VARCHAR(191) NOT NULL,
    converted_by_name VARCHAR(255) NOT NULL,
    transfer_public_id BIGINT UNSIGNED NULL,
    task_id BIGINT UNSIGNED NULL,
    canceled_at DATETIME(6) NULL,
    canceled_by_id VARCHAR(191) NOT NULL,
    canceled_by_name VARCHAR(255) NOT NULL,
    recorded_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_stock_transfer_request_revisions_number (request_id, revision_no),
    KEY ix_stock_transfer_request_revisions_hash (request_id, state_hash),
    KEY ix_stock_transfer_request_revisions_status (request_status, recorded_at),
    CONSTRAINT fk_stock_transfer_request_revisions_record FOREIGN KEY (request_id) REFERENCES stock_transfer_request_records (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_stock_transfer_request_revisions_number CHECK (revision_no > 0),
    CONSTRAINT chk_stock_transfer_request_revisions_source CHECK (source_kind IN ('bitrix_backfill', 'bitrix_dual_write', 'repair')),
    CONSTRAINT chk_stock_transfer_request_revisions_kind CHECK (request_kind IN ('transfer', 'supply')),
    CONSTRAINT chk_stock_transfer_request_revisions_status CHECK (request_status IN ('pending', 'converted', 'canceled')),
    CONSTRAINT chk_stock_transfer_request_revisions_note CHECK (CHAR_LENGTH(note) <= 500)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
