CREATE TABLE IF NOT EXISTS inventory_points (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    inventory_id BIGINT UNSIGNED NOT NULL,
    point_ordinal INT UNSIGNED NOT NULL,
    store_id BIGINT NOT NULL,
    store_name VARCHAR(191) NOT NULL,
    point_status VARCHAR(16) CHARACTER SET ascii NOT NULL,
    responsible_id VARCHAR(191) NOT NULL,
    responsible_name VARCHAR(255) NOT NULL,
    started_at DATETIME(6) NULL,
    submitted_at DATETIME(6) NULL,
    act_at DATETIME(6) NULL,
    snapshot_version TINYINT UNSIGNED NULL,
    snapshot_captured_at DATETIME(6) NULL,
    snapshot_migrated_at DATETIME(6) NULL,
    draft_updated_at DATETIME(6) NULL,
    draft_updated_by_id VARCHAR(191) NOT NULL,
    draft_updated_by_name VARCHAR(255) NOT NULL,
    draft_session_id VARCHAR(80) NOT NULL,
    draft_sequence BIGINT UNSIGNED NOT NULL DEFAULT 0,
    result_total INT UNSIGNED NULL,
    result_counted INT UNSIGNED NULL,
    result_discrepancies INT UNSIGNED NULL,
    is_present TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_inventory_points_store (inventory_id, store_id),
    KEY ix_inventory_points_order (inventory_id, is_present, point_ordinal),
    KEY ix_inventory_points_status (point_status, is_present, draft_updated_at),
    CONSTRAINT fk_inventory_points_record FOREIGN KEY (inventory_id) REFERENCES inventory_records (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_points_ordinal CHECK (point_ordinal > 0),
    CONSTRAINT chk_inventory_points_store CHECK (store_id <> 0 AND CHAR_LENGTH(store_name) > 0),
    CONSTRAINT chk_inventory_points_status CHECK (point_status IN ('idle', 'in_progress', 'submitted', 'act', 'reconciled')),
    CONSTRAINT chk_inventory_points_present CHECK (is_present IN (0, 1)),
    CONSTRAINT chk_inventory_points_snapshot CHECK ((snapshot_version IS NULL AND snapshot_captured_at IS NULL) OR (snapshot_version = 1 AND snapshot_captured_at IS NOT NULL)),
    CONSTRAINT chk_inventory_points_result CHECK ((result_total IS NULL AND result_counted IS NULL AND result_discrepancies IS NULL) OR (result_total IS NOT NULL AND result_counted IS NOT NULL AND result_discrepancies IS NOT NULL AND result_counted <= result_total AND result_discrepancies <= result_counted))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
