CREATE TABLE IF NOT EXISTS inventory_erp_documents (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    point_id BIGINT UNSIGNED NOT NULL,
    document_kind VARCHAR(32) CHARACTER SET ascii NOT NULL,
    erp_doctype VARCHAR(32) CHARACTER SET ascii NOT NULL,
    erp_document_name VARCHAR(191) NOT NULL,
    document_status VARCHAR(16) CHARACTER SET ascii NOT NULL,
    line_count INT UNSIGNED NOT NULL,
    saved_at DATETIME(6) NULL,
    submitted_at DATETIME(6) NULL,
    is_present TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_inventory_erp_documents_kind (point_id, document_kind),
    UNIQUE KEY uq_inventory_erp_documents_name (erp_doctype, erp_document_name),
    CONSTRAINT fk_inventory_erp_documents_point FOREIGN KEY (point_id) REFERENCES inventory_points (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_erp_documents_kind CHECK (document_kind IN ('legacy_reconciliation', 'issue', 'receipt')),
    CONSTRAINT chk_inventory_erp_documents_type CHECK ((document_kind = 'legacy_reconciliation' AND erp_doctype = 'Stock Reconciliation') OR (document_kind IN ('issue', 'receipt') AND erp_doctype = 'Stock Entry')),
    CONSTRAINT chk_inventory_erp_documents_status CHECK (document_status IN ('draft', 'submitted')),
    CONSTRAINT chk_inventory_erp_documents_present CHECK (is_present IN (0, 1)),
    CONSTRAINT chk_inventory_erp_documents_name CHECK (CHAR_LENGTH(erp_document_name) > 0),
    CONSTRAINT chk_inventory_erp_documents_submitted CHECK ((document_status = 'draft') OR (document_status = 'submitted' AND submitted_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
